[tool.briefcase]
project_name = "Apple Card to Mint Importer"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/applecardtomintimporter"
license = "MIT license"
author = 'Spencer Newton'
author_email = "spencer@example.com"

[tool.briefcase.app.applecardtomintimporter]
formal_name = "Apple Card to Mint Importer"
description = "Import your CSV Apple Card statements to Mint to properly track transactions!"
icon = "src/applecardtomintimporter/resources/applecardtomintimporter"
sources = ['src/applecardtomintimporter']
requires = []


[tool.briefcase.app.applecardtomintimporter.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.applecardtomintimporter.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.applecardtomintimporter.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.applecardtomintimporter.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.applecardtomintimporter.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
