[tool.briefcase]
project_name = "Apple Card to Mint Importer"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/applecardtomintimporter"
license = "MIT license"
author = 'Spencer Newton'
author_email = "spencer@example.com"

[tool.briefcase.app.applecardtomintimporter]
formal_name = "Apple Card to Mint Importer"
description = "Import your CSV Apple Card statements to Mint to properly track transactions!"
icon = "src/applecardtomintimporter/resources/applecardtomintimporter"
sources = ['src/applecardtomintimporter']
requires = [
	'arrow>=1.1.0',
	'binaryornot>=0.4.4',
	'briefcase>=0.3.5',
	'certifi>=2020.12.5',
	'chardet>=4.0.0',
	'click>=8.0.0',
	'cookiecutter>=1.7.2',
	'dmgbuild>=1.4.2',
	'ds-store>=1.3.0',
	'gitdb>=4.0.7',
	'GitPython>=3.1.16',
	'idna>=2.10',
	'Jinja2>=2.11.3',
	'jinja2-time>=0.2.0',
	'mac-alias>=2.2.0',
	'MarkupSafe>=1.1.1',
	'pip>=21.0.1',
	'poyo>=0.5.0',
	'python-dateutil>=2.8.1',
	'python-slugify>=5.0.2',
	'requests>=2.25.1',
	'rubicon-objc>=0.4.0',
	'setuptools>=54.1.2',
	'six>=1.16.0',
	'smmap>=4.0.0',
	'text-unidecode>=1.3',
	'toga-cocoa>=0.3.0.dev27',
	'toga-core >=0.3.0.dev27',
	'toml>=0.10.2',
	'travertino>=0.1.3',
	'urllib3>=1.26.4',
	'wheel>=0.36.2',
]


[tool.briefcase.app.applecardtomintimporter.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.applecardtomintimporter.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.applecardtomintimporter.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.applecardtomintimporter.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.applecardtomintimporter.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
